<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icons\audio_file.png" />
    <None Remove="Icons\default_file.png" />
    <None Remove="Icons\folder.png" />
    <None Remove="Icons\image_file.png" />
    <None Remove="Icons\text_file.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\default_file.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\audio_file.png" />
    <Resource Include="Icons\folder.png" />
    <Resource Include="Icons\image_file.png" />
    <Resource Include="Icons\text_file.png" />
  </ItemGroup>

</Project>
